services:
  app:
    build:
      context: .
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    networks:
        - app-network

networks:
  app-network:
    driver: bridge
