FROM php:8.1-apache

ENV APACHE_DOCUMENT_ROOT /var/www/html

RUN sed -ri -e 's!/var/www/html!'${APACHE_DOCUMENT_ROOT}'!g' /etc/apache2/sites-available/000-default.conf

RUN echo "DirectoryIndex index.php index.html" >> /etc/apache2/apache2.conf

COPY ../ /var/www/html

